### ISSUE TITLE
Document known good versions 

### ISSUE THREAD

**Issue by rvanlaar** [timrid/construct-editor#29]
Hi,

I'm looking into ways to document a binary format hands on,
and hopefully work together with others on this.
construct together with the construct editor seems like a good match.
However installing construct-editor is very hard and an impediment for
collaboration.  

Could construct-editor document known working versions?

The problem is mainly with wxPython. 
Note: I did end up getting something working with Python3.9, poetry, pip and a github checkout of wxPython.

Here are the problems I had on ubuntu 22.04 which comes with python3.10.

Steps to reproduce:
- python3 -m venv .venv
- source .venv/bin/activate
- pip install construct-editor

Problem: ModuleNotFoundError: No module named 'attrdict'
- pip install attrdict
- pip install construct-editor
Problem:       ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

It seems wxpython is not compatible with python3.10.
gist with full log: https://gist.github.com/rvanlaar/adb5f440db3b7bf49076b1f7b96d2787

ps. I did get something working with python3.9 and poetry. Creating a venv with python3.9 on ub

**Comment by derpicknicker1** [comment]
I have the same Problem.
Any Solution?

**Comment by rvanlaar** [comment]
Closing this issue. 

The latest version of construct-editor (0.1.4) with latest wxpython (4.2.1) works out of the box on linux with python3.10.
